name: PR Merge Queue
on:
  # merge_group:
  #   types: [checks_requested]
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: PR Merge Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check build
        run: python migration_conflicts.py
