name: Validate code in the merge queue

on:
  merge_group:
    branches: ["main"]
  pull_request:
    branches: [""]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: check build
        run: node checkBundleSize.cjs > bundleSize.json && cat bundleSize.json
        if: ${{ github.event_name == 'merge_group' }}

      # - name: Archive bundleSize
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: bundleSize
      #     path: bundleSize.json

      # # Commit all changed files back to the repository
      # - uses: stefanzweifel/git-auto-commit-action@v5
