name: Merge Verification
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  verify:
    if: github.event.pull_ request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run verification
        run: python migration_conflicts.py
